version: '3' 

services:
  app:
    container_name: node-app
    image: node:17-alpine
    volumes:
      - ./app/:/app
    working_dir: /app
    command: npm install && node app.js
    ports:
      - '3000:3000'